#!/bin/bash
source config

if [[ $main_translation == "true" ]]; then
  source bin/main-outlines
  if [[ $enable_audio_bible == "true" ]]; then
    source bin/audio-outlines
  fi
  source bin/main-reading
elif [[ $main_translation == "false" ]]; then
  source bin/other-outlines
  if [[ $enable_audio_bible == "true" ]]; then
    source bin/audio-outlines
  fi
  source bin/other-reading
fi

source bin/cleanup
