#!/bin/bash

export long_title="${long_title_arr[book]}"
export short_title="${short_title_arr[book]}"
export standard_long_title="${standard_long_title_arr[book]}"
export standard_abbreviation="${standard_abbreviation_arr[book]}"
export standard_genre="${standard_genre_arr[book]}"
export chapter_max=${length_arr[book]}
