#!/bin/bash

source config

# initialize the bible file for all of the old/new testament
echo -e "# ${bible_name}\n\n## Contents\n\n[[${standard_testament_arr[0]}|${testament_arr[0]}]]\n[[${standard_testament_arr[39]}|${testament_arr[39]}]]" >>"${outline_dir}/${standard_bible_name}.md"
# initialize the old/new testament file for all of the genres
echo -e "# ${testament_arr[0]}\n\n## Contents\n\n[[${standard_genre_arr[0]}|${genre_arr[0]}]]\n[[${standard_genre_arr[5]}|${genre_arr[5]}]]\n[[${standard_genre_arr[17]}|${genre_arr[17]}]]\n[[${standard_genre_arr[19]}|${genre_arr[19]}]]\n[[${standard_genre_arr[22]}|${genre_arr[22]}]]\n[[${standard_genre_arr[27]}|${genre_arr[27]}]]" >>"${outline_dir}/${standard_testament_arr[0]}.md"
echo -e "# ${testament_arr[39]}\n\n## Contents\n\n[[${standard_genre_arr[39]}|${genre_arr[39]}]]\n[[${standard_genre_arr[43]}|${genre_arr[43]}]]\n[[${standard_genre_arr[44]}|${genre_arr[44]}]]\n[[${standard_genre_arr[57]}|${genre_arr[57]}]]\n[[${standard_genre_arr[65]}|${genre_arr[65]}]]" >>"${outline_dir}/${standard_testament_arr[39]}.md"
# initialize the genre file for all of the bible
echo -e "# ${genre_arr[0]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[0]}.md"
echo -e "# ${genre_arr[5]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[5]}.md"
echo -e "# ${genre_arr[17]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[17]}.md"
echo -e "# ${genre_arr[19]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[19]}.md"
echo -e "# ${genre_arr[22]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[22]}.md"
echo -e "# ${genre_arr[27]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[27]}.md"
echo -e "# ${genre_arr[39]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[39]}.md"
echo -e "# ${genre_arr[43]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[43]}.md"
echo -e "# ${genre_arr[44]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[44]}.md"
echo -e "# ${genre_arr[57]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[57]}.md"
echo -e "# ${genre_arr[65]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[65]}.md"

for ((book = 0; book < book_max; book++)); do
    source get-info
    # Create an overview file for each book of the Bible:
    echo -e "# ${long_title}\n\n## Contents\n" >>"${outline_dir}/${standard_short_title}.md"
    # Create an overview file for each book of the Bible:
    echo -e "[[${standard_short_title}|${long_title}]]" >>"${outline_dir}/${standard_genre}.md"

    for ((chapter = 1; chapter <= chapter_max; chapter++)); do
        if [[ $chapter -gt 1 ]]; then
            echo -en "[[${standard_short_title}${filename_separator}${chapter}${filename_separator}${standard_translation}|]]" >>"${outline_dir}/${standard_short_title}.md"
        else
            echo -en "[[${standard_short_title}${filename_separator}${chapter}${filename_separator}${standard_translation}|Start reading (${translation})]]" >>"${outline_dir}/${standard_short_title}.md"
        fi
    done
done
