#!/bin/bash

source config

# initialize the bible file for all of the old/new testament
echo -e "# ${bible_name}\n\n## Contents\n\n[[${standard_testament_arr[0]}|${testament_arr[0]}]]\n[[${standard_testament_arr[39]}|${testament_arr[39]}]]" >>"${outline_dir}/${standard_bible_name}.md"
# initialize the old/new testament file for all of the genres
echo -e "# ${testament_arr[0]}\n\n## Contents\n\n[[${standard_genre_arr[0]}|${genre_arr[0]}]]\n[[${standard_genre_arr[5]}|${genre_arr[5]}]]\n[[${standard_genre_arr[17]}|${genre_arr[17]}]]\n[[${standard_genre_arr[19]}|${genre_arr[19]}]]\n[[${standard_genre_arr[22]}|${genre_arr[22]}]]\n[[${standard_genre_arr[27]}|${genre_arr[27]}]]" >>"${outline_dir}/${standard_testament_arr[0]}.md"
echo -e "# ${testament_arr[39]}\n\n## Contents\n\n[[${standard_genre_arr[39]}|${genre_arr[39]}]]\n[[${standard_genre_arr[43]}|${genre_arr[43]}]]\n[[${standard_genre_arr[44]}|${genre_arr[44]}]]\n[[${standard_genre_arr[57]}|${genre_arr[57]}]]\n[[${standard_genre_arr[65]}|${genre_arr[65]}]]" >>"${outline_dir}/${standard_testament_arr[39]}.md"
# initialize the genre file for all of the bible
echo -e "# ${genre_arr[0]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[0]}.md"
echo -e "# ${genre_arr[5]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[5]}.md"
echo -e "# ${genre_arr[17]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[17]}.md"
echo -e "# ${genre_arr[19]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[19]}.md"
echo -e "# ${genre_arr[22]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[22]}.md"
echo -e "# ${genre_arr[27]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[27]}.md"
echo -e "# ${genre_arr[39]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[39]}.md"
echo -e "# ${genre_arr[43]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[43]}.md"
echo -e "# ${genre_arr[44]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[44]}.md"
echo -e "# ${genre_arr[57]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[57]}.md"
echo -e "# ${genre_arr[65]}\n\n## Contents\n" >>"${outline_dir}/${standard_genre_arr[65]}.md"

for ((book = 0; book < book_max; book++)); do
    source fetch-info
    # Create an overview file for each book of the Bible:
    echo -e "# ${long_title}\n\n## Contents\n" >>"${outline_dir}/${standard_short_title}.md"
    # Create an overview file for each book of the Bible:
    echo -e "[[${standard_short_title}|${long_title}]]" >>"${outline_dir}/${standard_genre}.md"

    for ((chapter = 1; chapter <= chapter_max; chapter++)); do
        if [[ $chapter -gt 1 ]]; then
            echo -en "[[${standard_short_title}${filename_separator}${chapter}${filename_separator}${standard_translation}|]]" >>"${outline_dir}/${standard_short_title}.md"
        else
            echo -en "[[${standard_short_title}${filename_separator}${chapter}${filename_separator}${standard_translation}|Start reading ${translation}]]" >>"${outline_dir}/${standard_short_title}.md"
        fi
    done
done

# Name of the audio Bible file
# Initialize audio Bible file
echo -e "## ${audio_bible_name}\n" >>"${outline_dir}/${standard_audio_bible_name}.md"

for ((book = 0; book < book_max; book++)); do
    short_title="${short_title_arr[book]}"
    standard_short_title="${standard_short_title_arr[book]}"
    standard_abbreviation="${standard_abbreviation_arr[book]}"
    chapter_max=${length_arr[book]}

    if [[ $book != 0 ]]; then
        ((previous_book_num = book - 1))
    fi
    ((next_book_num = book + 1))

    previous_book="${standard_short_title_arr[previous_book_num]}"
    next_book="${standard_short_title_arr[next_book_num]}"

    if [[ $yaml_enabled == "true" ]]; then
        yaml="---\naliases: ${short_title}, ${short_title} (${translation}), ${abbreviation}, ${abbreviation} (${translation}), ${standard_abbreviation}, ${standard_abbreviation}${filename_separator}${translation}\n---"
        echo -e "${yaml}\n" >>"${outline_dir}/${standard_short_title}${filename_separator}${audio}.md"
    fi

    for ((chapter = 1; chapter <= chapter_max; chapter++)); do
        title="${short_title} ${chapter}"
        audio_bible="![[${standard_short_title}${filename_separator}${chapter}${filename_separator}${standard_translation}.mp3]]" # Setting the current file
        echo -e "${title}\n${audio_bible}" >>"${outline_dir}/${standard_short_title}${filename_separator}${audio}.md"
    done

    # Formatting Navigation and omitting links that aren't necessary
    if [[ $book -eq 0 ]]; then
        # For Genesis
        navigation="\n[[${standard_audio_bible_name}|All books]]\n[[${next_book}${filename_separator}${audio}|Next book]]"
    elif [[ $book -eq 65 ]]; then
        # For Revelation
        navigation="\n[[${standard_audio_bible_name}|All books]]\n[[${previous_book}${filename_separator}${audio}|Previous book]]"
        # For every other book
    else
        # Navigation for everything else
        navigation="\n[[${standard_audio_bible_name}|All books]]\n[[${previous_book}${filename_separator}${audio}|Previous book]]\n[[${next_book}-audio|Next book]]"
    fi

    if [[ "${navigation}" != "" ]]; then
        echo -e "${navigation}" >>"${outline_dir}/${standard_short_title}${filename_separator}${audio}.md"
    fi

    echo -e "[[${standard_short_title}${filename_separator}${audio}|${short_title}]]" >>"${outline_dir}/${standard_audio_bible_name}.md"
done
