#!/bin/bash

text=$(cat ~/Documents/obsidian/Christianity/Bible/LSB/Reading/$1.md)

# remove headings
text=$(echo "$text" | sed -E '1,3{d}')
text=$(echo "$text" | sed -E 's/^(# |## |##### ).*//')

# format verses
text=$(echo "$text" | sed -E 's/###### (¶* *[0-9][0-9][0-9])/\1 templine/g')
text=$(echo "$text" | sed -E 's/###### (¶* *[0-9][0-9])/\1  templine/g')
text=$(echo "$text" | sed -E 's/###### (¶* *[0-9])/\1   templine/g')
text=$(echo "$text" | sed -E ':a;$!{N;s/templine\n//;ba;}')
text=$(echo "$text" | sed -E 's/¶ (.*)/\1 ¶/g')

# remove markdown syntax
text=$(echo "$text" | sed -E 's/\*//g')
text=$(echo "$text" | sed -E 's/^> /      /g')
text=$(echo "$text" | sed -E 's/> /    /g')

# fit to terminal width
width=$(tput cols)
text=$(echo "$text" | sed "s/^\(.\{$((width - 1))\}\)./&    /")
text=$(echo "$text" | sed "s/^\(.\{$((width * 2 - 1))\}\)./&    /")
text=$(echo "$text" | sed "s/^\(.\{$((width * 3 - 1))\}\)./&    /")
text=$(echo "$text" | sed -E 's/([0-9]{1})    /\1   /g')
text=$(echo "$text" | sed -E 's/([0-9]{2})   /\1  /g')
text=$(echo "$text" | sed -E 's/([0-9]{3})  /\1 /g')

# fix poetry

# remove blank lines
text=$(echo "$text" | sed -E 's/ *$//g')
text=$(echo "$text" | sed -E '/^$/d')

if [[ $2 != '' ]]; then
  text=$(echo "$text" | sed -E ':a;$!{N;s/\n   //;ba;}')
  echo "$text" | GREP_COLORS='ms=01;31' grep -E --color=always "^${2} .*" -A2 -B2 | less -RFX
else
  echo "$text" | less -FX
fi
