#!/bin/bash

source config

if [[ $verbose == "true" ]]; then
    printf 'Starting download of the %s Bible.' "${translation}"
fi

# Cycling through the book counter, setting which book and its max chapter
((book = 0))
for ((book = 0; book < book_max; book++)); do
    source get-info

    if [[ $verbose == "true" ]]; then
        printf '\n%s' "${short_title}"
    fi

    if [[ $book != 0 ]]; then
        ((previous_book_num = book - 1))
    fi
    ((next_book_num = book + 1))

    previous_book="${standard_short_title_arr[previous_book_num]}"
    next_book="${standard_short_title_arr[next_book_num]}"

    for ((chapter = 1; chapter <= chapter_max; chapter++)); do
        if [[ $verbose == "true" ]]; then
            echo -n "."
        fi

        ((prevchapter = chapter - 1)) # Counting the previous and next chapter for navigation
        ((nextchapter = chapter + 1))

        # Exporting
        curr_file="${standard_short_title}${filename_separator}${chapter}${filename_separator}${standard_translation}"         # Setting the current file
        curr_file_notes="${standard_short_title}${filename_separator}${chapter}${filename_separator}${notes}"                  # Setting the current file
        previous_file="${standard_short_title}${filename_separator}${prevchapter}${filename_separator}${standard_translation}" # Naming previous and next files
        next_file="${standard_short_title}${filename_separator}${nextchapter}${filename_separator}${standard_translation}"

        if [[ $enable_audio_bible == "true" ]]; then
            audio_bible="![[${curr_file}.mp3]]"
        fi

        contents="## Contents\n\n[[${curr_file_notes}|Chapter notes]]"

        # Formatting Navigation and omitting links that aren't necessary
        if [[ $chapter_max -eq 1 ]]; then
            # For a book that only has one chapter
            navigation="${contents}\n\n## Related\n\n[[${previous_book}${filename_separator}${length_arr[$previous_book_num]}${filename_separator}${standard_translation}|Previous book]]\n[[${next_book}${filename_separator}1${filename_separator}${standard_translation}|Next book]]"
        elif [[ $chapter -eq $chapter_max ]] && [[ $book -eq $((book_max - 1)) ]]; then
            # If this is the last chapter of the book
            navigation="${contents}\n\n## Related\n\n[[${previous_file}|Previous chapter]]"
        elif [[ $chapter -eq $chapter_max ]] && [[ $book -ne $book_max ]]; then
            # If this is the last chapter of the book
            navigation="${contents}\n\n## Related\n\n[[${previous_file}|Previous chapter]]\n[[${next_book}${filename_separator}1${filename_separator}${standard_translation}|Next book]]"
        elif [[ ${chapter} -eq 1 ]] && [[ $book -eq $((book_max - 1)) ]]; then
            # If this is the first chapter of the book
            navigation="${contents}\n\n## Related\n\n[[${next_file}|Next chapter]]"
        elif [[ ${chapter} -eq 1 ]] && [[ $book -ne 0 ]]; then
            # If this is the first chapter of the book
            navigation="${contents}\n\n## Related\n\n[[${previous_book}${filename_separator}${length_arr[$previous_book_num]}${filename_separator}${standard_translation}|Previous book]]\n[[${next_file}|Next chapter]]"
        else
            # Navigation for everything else
            navigation="${contents}\n\n## Related\n\n[[${previous_file}|Previous chapter]]\n[[${next_file}|Next chapter]]"
        fi

        text=$(ruby bg2md.rb -e -c -f -l -r -v "${translation}" "${short_title} ${chapter}") # This calls the 'bg2mdmod' script
        # text=$(echo "${text}" | sed 's/^(.*?)v1/v1/') # Deleting unwanted headers
        text="${text/^(.*?)v1/v1/}" # Deleting unwanted headers

        yaml="---\naliases: ${short_title} ${chapter} ${translation}, ${short_title} ${chapter}, ${abbreviation} ${chapter} ${translation}, ${abbreviation} ${chapter}, ${standard_abbreviation}${chapter}, ${standard_abbreviation}${chapter}${standard_translation}\n---"

        if [[ $yaml_enabled == "true" ]] && [[ $enable_audio_bible == "true" ]]; then
            echo -e "${yaml}\n# ${short_title} ${chapter} ${translation}\n\n${audio_bible}\n${text}\n\n${navigation}" >>"${reading_dir}/${curr_file}.md"
        elif [[ $yaml_enabled == "true" ]] && [[ $enable_audio_bible == "false" ]]; then
            echo -e "${yaml}\n# ${short_title} ${chapter} ${translation}\n\n${text}\n\n${navigation}" >>"${reading_dir}/${curr_file}.md"
        elif [[ $yaml_enabled == "false" ]] && [[ $enable_audio_bible == "true" ]]; then
            echo -e "# ${short_title} ${chapter} ${translation}\n\n${audio_bible}\n${text}\n\n${navigation}" >>"${reading_dir}/${curr_file}.md"
        else
            echo -e "# ${short_title} ${chapter} ${translation}\n\n${text}\n\n${navigation}" >>"${reading_dir}/${curr_file}.md"
        fi

        # Export
        echo -e "# ${short_title} ${chapter}\n\n${audio_bible}\n${text}\n\n${navigation}" >>"${reading_dir}/${curr_file_notes}.md"
    done # End of the book exporting loop
done
